name: ASP.NET Core CI/CD

on:
  push:
    branches: [main] # əgər başqa branch-dəsənsə, onu yaz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # və ya hansını istifadə edirsənsə

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ./AzureLogin/AzureLogin.App.csproj --no-restore --configuration Release

      - name: Publish app
        run: dotnet publish ./AzureLogin/AzureLogin.App.csproj -c Release -o publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: AzureLoginApp # Azure App Service adını buraya yaz
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish
